memoria: memoria.c
	gcc -Wall -I/home/utnso/stranger-things/tp-2017-1c-Stranger-Code/shared-library -L/home/utnso/stranger-things/tp-2017-1c-Stranger-Code/shared-library/shared-library memoria.c -lshared-library -lcommons -lpthread -o memoria
